---
# Configures Regal rules, see https://docs.styra.com/regal/category/rules

# In most cases, consider addressing violations even if it requires restructuring the code. Chances
# are that this will improve the code quality. If that is not feasible, then consider using an
# inline comment to ignore the rule at a particular place. As a last resort, add an entry here. If
# so, be sure to include a comment explaining why. Avoid turning violations into warnings as these
# make it difficult to detect when a new issue is detected and they end up being ignored and
# cluttering the output.
rules:
  style:
    todo-comment:
      # We use TODO comments through out the code base to indicate work that
      # needs further refinement.
      level: ignore
    external-reference:
      # Although not using external-references in some places is a good idea, it can
      # quickly turn into a hot mess of parameters being passed around.
      level: ignore
    rule-length:
      # The test rules can be quite verbose as most of them use hard-coded data
      # which is very useful in tests.
      ignore:
        files:
          - "*_test.rego"
    file-length:
      ignore:
        files:
          # schemas can be quite large.
          - "*_schema.rego"
    line-length:
      ignore:
        files:
          # schemas can have very long attribute values, e.g. description.
          - "*_schema.rego"
          # This is generated by `make sync-test-data` and has many long lines
          - policy/lib/tekton/recorded_att_data_test.rego
  idiomatic:
    no-defined-entrypoint:
      level: ignore

ignore:
  files:
    # Avoid following the symlink to the top level policy dir
    - antora/docs/policy/**
