# Configures Regal rules, see https://docs.styra.com/regal/category/rules
---
rules:
  style:
    todo-comment:
      level: warning
    file-length:
      level: warning
    line-length:
      max-line-length: 130
