---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: '15:00'
      timezone: Etc/UTC
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: weekly
      time: '15:00'
      timezone: Etc/UTC
  - package-ecosystem: "npm"
    directory: "/antora/ec-policies-antora-extension"
    schedule:
      interval: weekly
      time: '15:00'
      timezone: Etc/UTC
