---
runtime:
  cache_dir: ./.cache/antora
  log:
    failure_level: warn
site:
  title: Rego policies related to HACBS Enterprise Contract
  url: https://hacbs-contract.github.io/ec-policies/
  start_page: ec-policies::index.adoc
  robots: allow
content:
  sources:
    - url: .
      start_path: ./antora/docs
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./antora/supplemental-ui
output:
  dir: ./public
antora:
  extensions:
  #
  # Uncomment to use the package from npm. If this doesn't
  # work then the downstream build will be broken.
  #- require: '@hacbs-contract/ec-policies-antora-extension'
  #
  # For our own builds and for hacking it's convenient to use the
  # extension directly from its local directory.
  - require: './antora/ec-policies-antora-extension/index.js'
