---
name: pre-merge-ci

on:
  pull_request:
    branches:
    - main

  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  all-tests-and-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install opa
      run: make install-opa OPA_BIN=$HOME/.local/bin

    - name: Install tkn
      uses: jerop/tkn@v0.1.0

    - name: Run checks
      run: make ci

    - name: Validate added bundles
      run: ./hack/validate-acceptable-bundles.sh

    - name: Upload test coverage report
      uses: codecov/codecov-action@v3
      if: always()
