---
name: pre-merge-ci

on:
  pull_request:
    branches:
    - main

  push:
    branches:
    - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  all-tests-and-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Setup Go environment
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version-file: go.mod
        cache: true

    - name: Run checks
      run: make ci

    # See https://issues.redhat.com/browse/HACBS-2391 to re-enable these checks
    # - name: Validate added bundles
    #   run: ./hack/validate-acceptable-bundles.sh

    - name: Upload test coverage report
      uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
      if: always()
