---
name: npm-publish-antora-extension

"on":
  push:
    branches:
    - main
    paths:
    - 'antora/ec-policies-antora-extension/**'

jobs:
  release-antora-extension:
    name: Release to NPM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Publish npm package
      run: make npm-publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
