---
name: npm-publish-antora-extension

"on":
  push:
    branches:
    - main
    paths:
    - 'antora/ec-policies-antora-extension/**'

permissions:
  contents: read

jobs:
  release-antora-extension:
    name: Release to NPM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Setup node
      uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
      with:
        cache: 'npm'
        cache-dependency-path: 'antora/ec-policies-antora-extension/package-lock.json'
        node-version-file: 'antora/ec-policies-antora-extension/package.json'

    - name: Publish npm package
      run: make npm-publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
